//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PasaElDato_v2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class pasaelda_PasaelDatoEntities : DbContext
    {
        public pasaelda_PasaelDatoEntities()
            : base("name=pasaelda_PasaelDatoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<categoria> categoria { get; set; }
        public virtual DbSet<comentario> comentario { get; set; }
        public virtual DbSet<comuna> comuna { get; set; }
        public virtual DbSet<direccion> direccion { get; set; }
        public virtual DbSet<email> email { get; set; }
        public virtual DbSet<empresa> empresa { get; set; }
        public virtual DbSet<estado> estado { get; set; }
        public virtual DbSet<horas> horas { get; set; }
        public virtual DbSet<imagen_producto> imagen_producto { get; set; }
        public virtual DbSet<imagen_sucursal> imagen_sucursal { get; set; }
        public virtual DbSet<medios_pago> medios_pago { get; set; }
        public virtual DbSet<producto> producto { get; set; }
        public virtual DbSet<puntaje> puntaje { get; set; }
        public virtual DbSet<puntaje_x_categoria> puntaje_x_categoria { get; set; }
        public virtual DbSet<region> region { get; set; }
        public virtual DbSet<reserva> reserva { get; set; }
        public virtual DbSet<restricciones> restricciones { get; set; }
        public virtual DbSet<servicio_habitacion> servicio_habitacion { get; set; }
        public virtual DbSet<servicio_motel> servicio_motel { get; set; }
        public virtual DbSet<sucursal> sucursal { get; set; }
        public virtual DbSet<telefono> telefono { get; set; }
        public virtual DbSet<tipo_habitacion> tipo_habitacion { get; set; }
        public virtual DbSet<tipo_usuario> tipo_usuario { get; set; }
        public virtual DbSet<tipohabitacion_x_sucursal> tipohabitacion_x_sucursal { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
    
        public virtual ObjectResult<MenuIndex_Result> MenuIndex()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MenuIndex_Result>("MenuIndex");
        }
    }
}
